### ISSUE TITLE
Add Ashtadhyayi Sutrapatha

### ISSUE THREAD

**Issue by hrishikeshrt** [avinashvarna/audio_alignment#5]
Text is available from ashtadhyayi.com/ (I can push text files in)
One source for audio is http://surasa.net/music/samskrta-vani/ashtadhyayi.php
Another is https://www.sanskritfromhome.in/course/ashtadhyayi/ (While this one is not freely available, it is very precise and devoid of some occasional errors, thus more useful for someone trying to learn to chant/memorise)

I tried aligning both versions. I am not sure if it's my system or it's about the nature of the text, but the alignments I obtained are pretty bad.

**Comment by hrishikeshrt** [comment]
Pushed the ashtadhyayi alignment as well. Managed to figure out why the alignment was poor, culprit being improper installation of `aeneas`.

Short version is,
1. Install using `pip install aeneas`, *not* `pip install py3-aeneas` even if latter seems like an updated fork.
2. Don't forget to apt-install `libespeak-dev` (on top of `ffprobe, ffmpeg, espeak`)

**Comment by avinashvarna** [comment]
Thanks. I should have added these notes to the README (at least installing `aeneas` and the other libs). Will do that, set up a GH action and merge this PR.

**Comment by avinashvarna** [comment]
Closed via PR #4
